# [span_8](start_span)Spring Boot Configuration[span_8](end_span)
spring.application.name=EcommerceApi
server.port=8080

# For easier reading of JSON API responses
spring.jackson.serialization.indent_output=true
